apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ip-reverser.fullname" . }}
  labels:
    {{- include "ip-reverser.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "ip-reverser.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ip-reverser.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.port }}
              name: http
          env:
            - name: PORT
              value: "{{ .Values.container.port }}"
            - name: PGHOST
              value: "{{ .Release.Name }}-postgresql"
            - name: PGUSER
              value: "postgres"
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-postgresql
                  key: postgres-password
